services:
  - type: web
    name: File-Manager-2.0-project-showcase
    env: node # O selecciona "Other" si está disponible
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y php
      echo "No build steps required"
    startCommand: "php -S 0.0.0.0:$PORT -t login"
    envVars:
      - key: DATABASE_URL
        value: ${my-database.internal.connectionString}
      - key: PORT
        value: "10000"

databases:
  - name: my-database
    plan: free
    mysqlVersion: 8
    envVars:
      - key: MYSQL_DATABASE
        value: "login"
      - key: MYSQL_USER
        value: "root"
      - key: MYSQL_PASSWORD
        value: "1d0ntw4nn4kn0w"
      - key: MYSQL_ROOT_PASSWORD
        value: "1d0ntw4nn4kn0w"
